#!/bin/bash

# Script Run Location = /home/plr/Repo/plr-alpi/4-Restore Xfce4 Config/restore_xfce4_configs/

rm -f *.txt

tput bold
echo -e "\e[1;34mDelete old configs...\e[1;37m";
tput sgr0

#delete all current xfce4 restore configs
sudo rm -rf dconf gtk-3.0 Thunar xfce4 
echo " "


tput bold
echo -e "\e[1;34mBackup new configs...\e[1;37m";
tput sgr0

#Copy new configs
cd /home/plr/.config/
cp -R dconf/ gtk-3.0/ Thunar/ xfce4/ ../Repo/plr-alpi/4-Backup\,Restore\ Xfce4\ Configs/backup\,restore-\(xfce4_configs\)/

#Insert a backup-date txt file
cd ../Repo/plr-alpi/4-Backup\,Restore\ Xfce4\ Configs/backup\,restore-\(xfce4_configs\)/
date > "Backup_time=$(date +"%Y.%m.%d-%I:%M%p").txt"




