#!/bin/bash

tput bold
echo -e "\e[1;32mCreate firefox Backup zip ...\e[1;37m";
tput sgr0
cd ../
tar -jcvf firefox-browser-profile.tar.bz2 .mozilla &&
mv firefox-browser-profile.tar.bz2 firefox-backup



