#!/bin/bash

rsync -av --no-links Applications/ /run/media/plr/DATA/linux-backup/Applications/ &&
rsync -av --no-links Documents/ /run/media/plr/DATA/linux-backup/Documents/ &&
rsync -av --no-links Desktop/ /run/media/plr/DATA/linux-backup/Desktop/ &&
rsync -av --no-links Downloads/ /run/media/plr/DATA/linux-backup/Downloads/ &&
rsync -av --no-links Music/ /run/media/plr/DATA/linux-backup/Music/ &&
rsync -av --no-links Pictures/ /run/media/plr/DATA/linux-backup/Pictures/ &&
rsync -av --no-links Videos/ /run/media/plr/DATA/linux-backup/Videos/ &&
rsync -av --no-links dotfiles/ /run/media/plr/DATA/linux-backup/dotfiles-backup/ &&
rsync -av --no-links My-Repos/ /run/media/plr/DATA/linux-backup/My-Repos-backup &&
rsync -av --no-links firefox-backup/ /run/media/plr/DATA/linux-backup/firefox-backup/ &&
rsync -av --no-links .ssh/ /run/media/plr/DATA/linux-backup/ssh-backup/ &&
rsync -av --no-links .mozilla/ /run/media/plr/DATA/linux-backup/firefox-backup/ 


 

