#!/bin/bash

rsync -av Applications/ /run/media/plr/DATA/linux-backup/Applications/ &&
rsync -av Documents/ /run/media/plr/DATA/linux-backup/Docuemnts/ &&
rsync -av Downloads/ /run/media/plr/DATA/linux-backup/Downloads/ &&
rsync -av Music/ /run/media/plr/DATA/linux-backup/Music/ &&
rsync -av Pictures/ /run/media/plr/DATA/linux-backup/Pictures/ &&
rsync -av Videos/ /run/media/plr/DATA/linux-backup/Videos/ &&
rsync -av dotfiles/ /run/media/plr/DATA/linux-backup/dotfiles-backup/ &&
rsync -av Repo/ /run/media/plr/DATA/linux-backup/Repo-backup 
 

