#!/bin/bash

rsync -av Applications/ /run/media/plr/DATA/LINUX_BACKUP/Applications/ &&
rsync -av Documents/ /run/media/plr/DATA/LINUX_BACKUP/Docuemnts/ &&
rsync -av Downloads/ /run/media/plr/DATA/LINUX_BACKUP/Downloads/ &&
rsync -av Music/ /run/media/plr/DATA/LINUX_BACKUP/Music/ &&
rsync -av Pictures/ /run/media/plr/DATA/LINUX_BACKUP/Pictures/ &&
rsync -av Videos/ /run/media/plr/DATA/LINUX_BACKUP/Videos/ &&
rsync -av dotfiles/ /run/media/plr/DATA/LINUX_BACKUP/dotfiles_backup/ &&
rsync -av Repo/ /run/media/plr/DATA/LINUX_BACKUP/Repo_backup 
 

