#!/bin/bash

rsync -av --no-links Applications/ /run/media/plr/DATA/linux-backup/Applications/ &&
rsync -av --no-links Documents/ /run/media/plr/DATA/linux-backup/Documents/ &&
rsync -av --no-links Desktop/ /run/media/plr/DATA/linux-backup/Desktop/ &&
rsync -av --no-links Downloads/ /run/media/plr/DATA/linux-backup/Downloads/ &&
rsync -av --no-links Music/ /run/media/plr/DATA/linux-backup/Music/ &&
rsync -av --no-links Pictures/ /run/media/plr/DATA/linux-backup/Pictures/ &&
rsync -av --no-links Videos/ /run/media/plr/DATA/linux-backup/Videos/ &&
rsync -av --no-links Videos/ /run/media/plr/DATA/linux-backup/Videos/ &&
rsync -av --no-links .mozilla/ /run/media/plr/DATA/linux-backup/ &&
rsync -av --no-links .ssh/ /run/media/plr/DATA/linux-backup/ &&
rsync -av --no-links .config/obsidian/ /run/media/plr/DATA/linux-backup/.config/ &&
rsync -av --no-links .config/Logseq/ /run/media/plr/DATA/linux-backup/.config/ &&
rsync -av --no-links .config/joplin-desktop/ /run/media/plr/DATA/linux-backup/.config/ &&
rsync -av --no-links .config/joplin/ /run/media/plr/DATA/linux-backup/.config/ &&
rsync -av --no-links .config/google-chrome/ /run/media/plr/DATA/linux-backup/.config/ &&
rsync -av --no-links .config/chromium/ /run/media/plr/DATA/linux-backup/.config/ &&
rsync -av --no-links My-Repos/ /run/media/plr/DATA/linux-backup/ &&
rsync -av --no-links dotfiles/ /run/media/plr/DATA/linux-backup/ &&




 